sonar.organization=jwp23
sonar.projectKey=jwp23_agent-downlink
sonar.sources=.
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.exclusions=docs/**
sonar.go.coverage.reportPaths=coverage.out
sonar.qualitygate.wait=true
